### ISSUE TITLE
BUG: sometimes in the profile-page-menu the "empty" articles/streams are not getting hidden

### ISSUE THREAD

**Issue by dwebert** [hzrd149/nostrudel#66]
![image](https://github.com/hzrd149/nostrudel/assets/18017148/bbe3bd6f-d7b5-4f0e-9fd0-316db7d861e7)

**Comment by hzrd149** [comment]
There isn't any code to hide the tabs, but this is something I've been wanting to fix. I've just put it off because I wanted to find a better solution than tabs before I fixed it

**Comment by hzrd149** [comment]
This may be fixed in the alpha version, at least I've added code to hide the tabs if no articles or stream events are found on at least 3 relays https://next.nostrudel.ninja/

**Comment by dwebert** [comment]
A few days ago, i think it worked. 
but git-version today. not working. still showing up :(
i also have another problem. Sometimes my badges show up, sometimes not.
